# Generated by Django 2.2.3 on 2019-08-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField()),
                ('q2', models.IntegerField()),
                ('q3', models.IntegerField()),
                ('q4', models.IntegerField()),
                ('q5', models.IntegerField()),
                ('q6', models.IntegerField()),
                ('q7', models.IntegerField()),
                ('q8', models.IntegerField()),
                ('qb1', models.BooleanField(default=False)),
                ('qb2', models.BooleanField(default=False)),
                ('qb3', models.BooleanField(default=False)),
                ('qb4', models.BooleanField(default=False)),
                ('more_info', models.CharField(max_length=1000)),
            ],
        ),
    ]
